### ISSUE TITLE
Obstructed content

### ISSUE THREAD

**Issue by TWiStErRob** [pyricau/pyricau.github.com#21]
The trick you use to be able to deep-link into an article obstructs the area above the heading.

Try clicking on the word "software" at:
> By the way, if you need excellent quality software translation, I know someone that's been translating software for more than 25 years. Yes, he is my father :) . -- http://www.piwai.info/android-string-placeholders/

![image](https://cloud.githubusercontent.com/assets/2906988/14175454/537973e0-f74b-11e5-997c-ae761c24d7cf.png)

To work around this you can minimize the impact of the "offset because overlay menu" hack:
```css
*:target::before {
	content: " ";
	width: 0;
	height: 0;
	display: block;
	padding-top: 50px;
	margin-top: -50px;
}
```
1. This will only add fake padding-margin when needed
2. The fake padding-margin area is not clickable

You can try this solution at http://www.twisterrob.net/project/inventory/ and you can find [source here](https://github.com/TWiStErRob/twisterrob.github.io/blob/master/_sass/_09_elements.scss#L179).
